import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';

// Mock classes for script execution
class Market {
  final String name;
  final String address;
  final String city;
  final String state;
  final double latitude;
  final double longitude;
  final String? placeId;
  final Map<String, String> operatingDays;
  final String? description;
  final String? imageUrl;
  final bool isActive;
  final DateTime createdAt;

  const Market({
    required this.name,
    required this.address,
    required this.city,
    required this.state,
    required this.latitude,
    required this.longitude,
    this.placeId,
    this.operatingDays = const {},
    this.description,
    this.imageUrl,
    this.isActive = true,
    required this.createdAt,
  });

  Map<String, dynamic> toFirestore() {
    return {
      'name': name,
      'address': address,
      'city': city,
      'state': state,
      'latitude': latitude,
      'longitude': longitude,
      'placeId': placeId,
      'operatingDays': operatingDays,
      'description': description,
      'imageUrl': imageUrl,
      'isActive': isActive,
      'createdAt': Timestamp.fromDate(createdAt),
    };
  }
}

enum VendorCategory {
  produce,
  dairy,
  meat,
  bakery,
  prepared_foods,
  beverages,
  flowers,
  crafts,
  skincare,
  clothing,
  jewelry,
  art,
  plants,
  honey,
  preserves,
  spices,
  other,
}

class ManagedVendor {
  final String marketId;
  final String organizerId;
  final String businessName;
  final String contactName;
  final String description;
  final List<VendorCategory> categories;
  final String? imageUrl;
  final List<String> imageUrls;
  final String? logoUrl;
  final String? email;
  final String? phoneNumber;
  final String? website;
  final String? instagramHandle;
  final String? facebookHandle;
  final String? address;
  final String? city;
  final String? state;
  final String? zipCode;
  final bool canDeliver;
  final bool acceptsOrders;
  final String? deliveryNotes;
  final List<String> products;
  final List<String> specialties;
  final String? priceRange;
  final bool isOrganic;
  final bool isLocallySourced;
  final String? certifications;
  final bool isActive;
  final bool isFeatured;
  final List<String> operatingDays;
  final String? boothPreferences;
  final String? specialRequirements;
  final String? story;
  final List<String> tags;
  final String? slogan;
  final DateTime createdAt;
  final DateTime updatedAt;
  final Map<String, dynamic> metadata;

  const ManagedVendor({
    required this.marketId,
    required this.organizerId,
    required this.businessName,
    required this.contactName,
    required this.description,
    this.categories = const [],
    this.imageUrl,
    this.imageUrls = const [],
    this.logoUrl,
    this.email,
    this.phoneNumber,
    this.website,
    this.instagramHandle,
    this.facebookHandle,
    this.address,
    this.city,
    this.state,
    this.zipCode,
    this.canDeliver = false,
    this.acceptsOrders = false,
    this.deliveryNotes,
    this.products = const [],
    this.specialties = const [],
    this.priceRange,
    this.isOrganic = false,
    this.isLocallySourced = false,
    this.certifications,
    this.isActive = true,
    this.isFeatured = false,
    this.operatingDays = const [],
    this.boothPreferences,
    this.specialRequirements,
    this.story,
    this.tags = const [],
    this.slogan,
    required this.createdAt,
    required this.updatedAt,
    this.metadata = const {},
  });

  Map<String, dynamic> toFirestore() {
    return {
      'marketId': marketId,
      'organizerId': organizerId,
      'businessName': businessName,
      'contactName': contactName,
      'description': description,
      'categories': categories.map((cat) => cat.name).toList(),
      'imageUrl': imageUrl,
      'imageUrls': imageUrls,
      'logoUrl': logoUrl,
      'email': email,
      'phoneNumber': phoneNumber,
      'website': website,
      'instagramHandle': instagramHandle,
      'facebookHandle': facebookHandle,
      'address': address,
      'city': city,
      'state': state,
      'zipCode': zipCode,
      'canDeliver': canDeliver,
      'acceptsOrders': acceptsOrders,
      'deliveryNotes': deliveryNotes,
      'products': products,
      'specialties': specialties,
      'priceRange': priceRange,
      'isOrganic': isOrganic,
      'isLocallySourced': isLocallySourced,
      'certifications': certifications,
      'isActive': isActive,
      'isFeatured': isFeatured,
      'operatingDays': operatingDays,
      'boothPreferences': boothPreferences,
      'specialRequirements': specialRequirements,
      'story': story,
      'tags': tags,
      'slogan': slogan,
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': Timestamp.fromDate(updatedAt),
      'metadata': metadata,
    };
  }
}

Future<void> main() async {
  print('🌱 Adding Dunwoody Farmers Market to HiPop Database...\n');

  try {
    // Initialize Firebase
    await Firebase.initializeApp();
    
    final firestore = FirebaseFirestore.instance;

    // Create Dunwoody Farmers Market with recurring Sunday schedule
    final market = Market(
      name: 'Dunwoody Farmers Market',
      address: '4800 Ashford Dunwoody Rd, Dunwoody, GA 30338',
      city: 'Dunwoody',
      state: 'GA',
      latitude: 33.9284,
      longitude: -84.3387,
      placeId: 'ChIJdwU_kQMP9YgRVcg6CXQlKbg',
      operatingDays: {
        'sunday': '9:00 AM - 1:00 PM',
      },
      description: 'Amazing local farmers market in Dunwoody featuring incredible vendors, fresh produce, artisanal goods, and community spirit. Perfect for stocking up on your favorites and discovering something new!',
      imageUrl: 'https://example.com/dunwoody_farmers_market.jpg',
      isActive: true,
      createdAt: DateTime.now(),
    );

    // Save market to Firestore
    final marketRef = await firestore.collection('markets').add(market.toFirestore());

    print('✅ Successfully added Dunwoody Farmers Market!');
    print('📍 Market ID: ${marketRef.id}');

    // Create all vendors from the announcement
    final vendors = [
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Weld ATL',
        contactName: 'Weld ATL Team',
        description: 'Permanent jewelry services creating custom pieces on-site',
        categories: [VendorCategory.jewelry, VendorCategory.crafts],
        products: ['Permanent jewelry', 'Custom jewelry', 'Welded bracelets', 'Welded necklaces'],
        specialties: ['On-site jewelry welding', 'Custom permanent jewelry'],
        instagramHandle: 'weld_atl',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['jewelry', 'permanent', 'custom', 'welded'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Joi Pet Treats',
        contactName: 'Joi Pet Treats Team',
        description: 'Single ingredient pet treats for your furry friends',
        categories: [VendorCategory.other],
        products: ['Single ingredient pet treats', 'Natural dog treats', 'Healthy pet snacks'],
        specialties: ['Single ingredient treats', 'Natural pet products'],
        instagramHandle: 'joipettreats',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['pet', 'treats', 'natural', 'single-ingredient'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Hero Brands ATL / Stone Mountain Cattle',
        contactName: 'Hero Brands Team',
        description: 'Local organic meats including chicken, pork, and beef',
        categories: [VendorCategory.meat],
        products: ['Organic chicken', 'Organic pork', 'Organic beef', 'Grass-fed meat'],
        specialties: ['Local organic meats', 'Sustainable farming'],
        instagramHandle: 'herobrandsatl',
        isOrganic: true,
        isLocallySourced: true,
        certifications: 'Organic',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['meat', 'organic', 'local', 'grass-fed'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Summit Coffee Dunwoody',
        contactName: 'Summit Coffee Team',
        description: 'Coffee drinks and fresh roasted beans',
        categories: [VendorCategory.beverages],
        products: ['Coffee drinks', 'Fresh roasted coffee beans', 'Specialty coffee', 'Espresso'],
        specialties: ['Fresh roasted coffee', 'Specialty coffee drinks'],
        instagramHandle: 'summitcoffeedunwoody',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['coffee', 'drinks', 'beans', 'fresh-roasted'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Herb RX Life',
        contactName: 'Herb RX Life Team',
        description: 'Loose leaf wellness tea blends for health and wellness',
        categories: [VendorCategory.beverages, VendorCategory.other],
        products: ['Loose leaf tea', 'Wellness tea blends', 'Herbal teas', 'Health teas'],
        specialties: ['Wellness tea blends', 'Herbal medicine'],
        instagramHandle: 'herbrxlife',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['tea', 'wellness', 'herbal', 'health'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Georgia Proud Provisions',
        contactName: 'Georgia Proud Team',
        description: 'Fresh Georgia fruits and pecans including peaches, strawberries, and blueberries',
        categories: [VendorCategory.produce],
        products: ['Georgia peaches', 'Fresh strawberries', 'Fresh blueberries', 'Georgia pecans'],
        specialties: ['Georgia grown fruit', 'Fresh seasonal produce'],
        instagramHandle: 'georgiaproudprovisions',
        isLocallySourced: true,
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['fruit', 'georgia', 'peaches', 'berries', 'pecans'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Blended Together Juice',
        contactName: 'Blended Together Team',
        description: 'Cold pressed juices made fresh with quality ingredients',
        categories: [VendorCategory.beverages],
        products: ['Cold pressed juice', 'Fresh juice blends', 'Healthy beverages'],
        specialties: ['Cold pressed juices', 'Fresh juice blends'],
        instagramHandle: 'blendedtogetherjuice',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['juice', 'cold-pressed', 'fresh', 'healthy'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Cupcake on the Rocks ATL',
        contactName: 'Cupcake on the Rocks Team',
        description: 'Delicious cupcake jars and brownies',
        categories: [VendorCategory.bakery],
        products: ['Cupcake jars', 'Brownies', 'Desserts', 'Baked goods'],
        specialties: ['Cupcake jars', 'Artisan brownies'],
        instagramHandle: 'cupcakeontherocksatl',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['cupcakes', 'brownies', 'desserts', 'jars'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Simply Done Donuts',
        contactName: 'Simply Done Team',
        description: 'Fresh donuts from our mobile donut food truck',
        categories: [VendorCategory.bakery, VendorCategory.prepared_foods],
        products: ['Fresh donuts', 'Glazed donuts', 'Specialty donuts', 'Coffee pairings'],
        specialties: ['Fresh made donuts', 'Food truck service'],
        instagramHandle: 'simplydonedonuts',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['donuts', 'food-truck', 'fresh', 'bakery'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Bespoke Events Atlanta',
        contactName: 'Bespoke Events Team',
        description: 'Build your own bouquet bar with fresh flowers',
        categories: [VendorCategory.flowers],
        products: ['Fresh flowers', 'DIY bouquets', 'Flower arrangements', 'Seasonal blooms'],
        specialties: ['Build your own bouquet', 'Fresh flower arrangements'],
        instagramHandle: 'bespokeeventsatlanta',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['flowers', 'bouquets', 'diy', 'fresh'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Britz Sno Blitz',
        contactName: 'Britz Sno Blitz Team',
        description: 'Refreshing shaved ice treats',
        categories: [VendorCategory.beverages, VendorCategory.prepared_foods],
        products: ['Shaved ice', 'Snow cones', 'Flavored ice treats', 'Refreshing drinks'],
        specialties: ['Shaved ice', 'Cool treats'],
        instagramHandle: 'britzsnoblitz',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['shaved-ice', 'treats', 'refreshing', 'cold'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Mitzva House',
        contactName: 'Mitzva House Team',
        description: 'Kosher baked goods made with traditional recipes',
        categories: [VendorCategory.bakery],
        products: ['Kosher baked goods', 'Traditional breads', 'Pastries', 'Kosher desserts'],
        specialties: ['Kosher baking', 'Traditional recipes'],
        instagramHandle: 'mitzvahouse',
        certifications: 'Kosher',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['kosher', 'baked-goods', 'traditional', 'breads'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Bad Rabbit Woodworks LLC',
        contactName: 'Bad Rabbit Team',
        description: 'Handmade charcuterie boards and woodworking crafts',
        categories: [VendorCategory.crafts],
        products: ['Handmade charcuterie boards', 'Wooden serving boards', 'Wood crafts', 'Custom woodwork'],
        specialties: ['Handmade charcuterie boards', 'Custom woodworking'],
        instagramHandle: 'badrabbitwoodworksllc',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['woodworking', 'charcuterie', 'handmade', 'crafts'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Just Good Clean Cookin',
        contactName: 'Just Good Clean Team',
        description: 'Healthy snack mixes and granola made with clean ingredients',
        categories: [VendorCategory.prepared_foods],
        products: ['Snack mixes', 'Granola', 'Healthy snacks', 'Clean ingredients'],
        specialties: ['Clean cooking', 'Healthy snacks'],
        instagramHandle: 'justgoodcleancookin_',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['snacks', 'granola', 'healthy', 'clean'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Face Paint Fairy Parties',
        contactName: 'Face Paint Fairy Team',
        description: 'Face painting and hair tinsel services for all ages',
        categories: [VendorCategory.other],
        products: ['Face painting', 'Hair tinsel', 'Body art', 'Party services'],
        specialties: ['Face painting', 'Hair tinsel', 'Party entertainment'],
        instagramHandle: 'facepaintfairyparties',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['face-paint', 'hair-tinsel', 'parties', 'entertainment'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Dancing Sourdough',
        contactName: 'Dancing Sourdough Team',
        description: 'Artisan sourdough breads and baked goods',
        categories: [VendorCategory.bakery],
        products: ['Sourdough bread', 'Artisan breads', 'Sourdough pastries', 'Fermented baked goods'],
        specialties: ['Sourdough baking', 'Artisan breads'],
        instagramHandle: 'dancingsourdough',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['sourdough', 'bread', 'artisan', 'fermented'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Marsianka Jewelry',
        contactName: 'Marsianka Team',
        description: 'Handcrafted jewelry and accessories',
        categories: [VendorCategory.jewelry],
        products: ['Handmade jewelry', 'Accessories', 'Custom jewelry', 'Artisan pieces'],
        specialties: ['Handcrafted jewelry', 'Custom designs'],
        instagramHandle: 'marsianka06',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['jewelry', 'handmade', 'accessories', 'custom'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Top Tier Gear Dog Dept',
        contactName: 'Top Tier Gear Team',
        description: 'Premium pet accessories and gear for your furry friends',
        categories: [VendorCategory.other],
        products: ['Pet accessories', 'Dog gear', 'Pet supplies', 'Premium pet products'],
        specialties: ['Premium pet accessories', 'Dog gear'],
        instagramHandle: 'toptiergear.dogdept',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['pet', 'accessories', 'dog', 'gear'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Ziparoos',
        contactName: 'Ziparoos Team',
        description: 'Reusable products for sustainable living',
        categories: [VendorCategory.other],
        products: ['Reusable bags', 'Sustainable products', 'Eco-friendly items', 'Zero waste products'],
        specialties: ['Reusable products', 'Sustainable living'],
        instagramHandle: 'ziparoos',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['reusable', 'sustainable', 'eco-friendly', 'zero-waste'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Kraftz by Kadin',
        contactName: 'Kadin',
        description: 'Handmade lip balm and pet paw balm',
        categories: [VendorCategory.skincare, VendorCategory.other],
        products: ['Lip balm', 'Pet paw balm', 'Natural skincare', 'Handmade balms'],
        specialties: ['Handmade balms', 'Natural skincare'],
        instagramHandle: 'kraftzbykadin',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['lip-balm', 'pet-care', 'handmade', 'natural'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Wandering Child Co',
        contactName: 'Wandering Child Team',
        description: 'Stylish and comfortable children\'s clothing',
        categories: [VendorCategory.clothing],
        products: ['Children\'s clothing', 'Kids apparel', 'Stylish kids clothes', 'Comfortable clothing'],
        specialties: ['Children\'s fashion', 'Quality kids clothing'],
        instagramHandle: 'wanderingchildco',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['children', 'clothing', 'kids', 'apparel'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Jami Sweet Treats',
        contactName: 'Jami',
        description: 'Frozen custard and cookies for sweet tooth satisfaction',
        categories: [VendorCategory.bakery, VendorCategory.prepared_foods],
        products: ['Frozen custard', 'Cookies', 'Sweet treats', 'Desserts'],
        specialties: ['Frozen custard', 'Homemade cookies'],
        instagramHandle: 'jamisweetreats',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['custard', 'cookies', 'desserts', 'treats'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Hot Nutz Food Truck',
        contactName: 'Hot Nutz Team',
        description: 'Hot boiled peanuts served fresh from our food truck',
        categories: [VendorCategory.prepared_foods],
        products: ['Hot boiled peanuts', 'Seasoned peanuts', 'Southern snacks'],
        specialties: ['Hot boiled peanuts', 'Food truck service'],
        instagramHandle: 'hotnutzfoodtruck',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['peanuts', 'food-truck', 'hot', 'southern'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Chef Frey\'s Kitchen',
        contactName: 'Chef Frey',
        description: 'Authentic Japanese cuisine and specialties',
        categories: [VendorCategory.prepared_foods],
        products: ['Japanese cuisine', 'Sushi', 'Japanese specialties', 'Asian dishes'],
        specialties: ['Japanese cooking', 'Authentic cuisine'],
        instagramHandle: 'cheffreys.kitchen',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['japanese', 'cuisine', 'sushi', 'authentic'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Fidelas Street Kitchen',
        contactName: 'Fidelas Team',
        description: 'Fresh tacos and empanadas with authentic flavors',
        categories: [VendorCategory.prepared_foods],
        products: ['Fresh tacos', 'Empanadas', 'Mexican food', 'Street food'],
        specialties: ['Authentic tacos', 'Fresh empanadas'],
        instagramHandle: 'fidelasstreetkitchen',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['tacos', 'empanadas', 'mexican', 'street-food'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Get Emmersed',
        contactName: 'Get Emmersed Team',
        description: 'Handmade soy wax candles for home ambiance',
        categories: [VendorCategory.crafts],
        products: ['Soy wax candles', 'Handmade candles', 'Scented candles', 'Home fragrance'],
        specialties: ['Handmade soy candles', 'Natural wax'],
        instagramHandle: 'getemmersed',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['candles', 'soy-wax', 'handmade', 'fragrance'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Grow with the Flow LLC',
        contactName: 'Grow with the Flow Team',
        description: 'Fresh organic vegetables grown with care',
        categories: [VendorCategory.produce],
        products: ['Organic vegetables', 'Fresh produce', 'Seasonal vegetables', 'Farm fresh'],
        specialties: ['Organic farming', 'Fresh vegetables'],
        instagramHandle: 'growwiththeflowllc',
        isOrganic: true,
        isLocallySourced: true,
        certifications: 'Organic',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['vegetables', 'organic', 'fresh', 'farm'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Cotton Caricatures',
        contactName: 'Cotton Caricatures Team',
        description: 'FREE caricature drawings for market visitors',
        categories: [VendorCategory.art],
        products: ['FREE caricatures', 'Portrait art', 'Entertainment', 'Art services'],
        specialties: ['Caricature art', 'Entertainment'],
        instagramHandle: 'cotton_caricatures',
        operatingDays: ['sunday'],
        acceptsOrders: false,
        priceRange: 'Free',
        tags: ['caricatures', 'art', 'free', 'entertainment'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Kim Lucretia Author',
        contactName: 'Kim Lucretia',
        description: 'Children\'s books and stories for young readers',
        categories: [VendorCategory.other],
        products: ['Children\'s books', 'Story books', 'Educational books', 'Young reader books'],
        specialties: ['Children\'s literature', 'Educational stories'],
        instagramHandle: 'kimlucretiaauthor',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['books', 'children', 'author', 'stories'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Slim Thick Vegan ATL',
        contactName: 'Slim Thick Vegan Team',
        description: 'Vegan and plant-based meal prep services',
        categories: [VendorCategory.prepared_foods],
        products: ['Vegan meal prep', 'Plant-based meals', 'Healthy prepared foods', 'Vegan dishes'],
        specialties: ['Vegan meal prep', 'Plant-based cooking'],
        instagramHandle: 'slimthickveganatl',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['vegan', 'plant-based', 'meal-prep', 'healthy'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Nai.Eve',
        contactName: 'Nai.Eve Team',
        description: 'Stylish women\'s clothing and fashion',
        categories: [VendorCategory.clothing],
        products: ['Women\'s clothing', 'Fashion apparel', 'Stylish clothing', 'Women\'s fashion'],
        specialties: ['Women\'s fashion', 'Stylish apparel'],
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['women', 'clothing', 'fashion', 'apparel'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Got Seafood Atlanta',
        contactName: 'Got Seafood Team',
        description: 'Fresh wild-caught seafood from sustainable sources',
        categories: [VendorCategory.meat],
        products: ['Wild-caught seafood', 'Fresh fish', 'Sustainable seafood', 'Ocean fish'],
        specialties: ['Wild-caught seafood', 'Sustainable fishing'],
        instagramHandle: 'got_seafood_atlanta',
        isLocallySourced: true,
        certifications: 'Sustainable seafood',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['seafood', 'wild-caught', 'sustainable', 'fresh'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Bee Wild Buzz',
        contactName: 'Bee Wild Team',
        description: 'Local raw honey and bee products',
        categories: [VendorCategory.honey],
        products: ['Local raw honey', 'Bee products', 'Natural honey', 'Honeycomb'],
        specialties: ['Local raw honey', 'Bee keeping'],
        instagramHandle: 'beewildbuzz',
        isLocallySourced: true,
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['honey', 'raw', 'local', 'bee'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Bleu\'s Hues',
        contactName: 'Bleu\'s Hues Team',
        description: 'Handmade watercolor paints and art supplies',
        categories: [VendorCategory.art],
        products: ['Handmade watercolor paints', 'Art supplies', 'Natural pigments', 'Artist materials'],
        specialties: ['Handmade watercolors', 'Natural pigments'],
        instagramHandle: 'bleus_hues',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['watercolor', 'paint', 'art', 'handmade'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Eat Right Atlanta',
        contactName: 'Eat Right Team',
        description: 'Fresh fruits and vegetables for healthy eating',
        categories: [VendorCategory.produce],
        products: ['Fresh fruits', 'Fresh vegetables', 'Healthy produce', 'Seasonal produce'],
        specialties: ['Fresh produce', 'Healthy eating'],
        instagramHandle: 'eatrightatlanta',
        operatingDays: ['sunday'],
        acceptsOrders: true,
        tags: ['fruits', 'vegetables', 'healthy', 'fresh'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ManagedVendor(
        marketId: marketRef.id,
        organizerId: 'dunwoody_market_organizer',
        businessName: 'Niles Rivers Live Music',
        contactName: 'Niles Rivers',
        description: 'Live music entertainment for the market atmosphere',
        categories: [VendorCategory.other],
        products: ['Live music', 'Musical entertainment', 'Acoustic performances', 'Market atmosphere'],
        specialties: ['Live music performance', 'Entertainment'],
        instagramHandle: 'officialnilesrivers',
        operatingDays: ['sunday'],
        acceptsOrders: false,
        tags: ['music', 'live', 'entertainment', 'acoustic'],
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
    ];

    // Save all vendors to Firestore
    final vendorRefs = <String>[];
    for (final vendor in vendors) {
      final vendorRef = await firestore.collection('managed_vendors').add(vendor.toFirestore());
      vendorRefs.add(vendorRef.id);
    }

    print('\n🎯 Successfully added Dunwoody Farmers Market data:');
    print('   📅 Recurring Sunday market (9:00 AM - 1:00 PM)');
    print('   🏪 ${vendors.length} amazing vendors');
    print('   📍 Location: 4800 Ashford Dunwoody Rd, Dunwoody, GA 30338');
    
    print('\n📋 Vendor Categories Added:');
    final categoryCount = <VendorCategory, int>{};
    for (final vendor in vendors) {
      for (final category in vendor.categories) {
        categoryCount[category] = (categoryCount[category] ?? 0) + 1;
      }
    }
    categoryCount.forEach((category, count) {
      print('   • ${category.name}: $count vendors');
    });

    print('\n🌟 Market Features:');
    print('   • Recurring Sunday schedule');
    print('   • 34 diverse vendors');
    print('   • Instagram integration for all vendors');
    print('   • Categories: produce, meat, bakery, prepared foods, beverages, jewelry, crafts, and more');
    print('   • Special features: FREE caricatures, live music, organic options');

    print('\n✅ Dunwoody Farmers Market is now ready for shoppers!');

  } catch (e) {
    print('❌ Error adding Dunwoody Farmers Market: $e');
    print('\n🔧 Alternative: Add this data manually through the app');
  }
}